name: Test
on: { push: , pull_request: }

jobs:
  test:
    strategy: { matrix: { node-version: [ ^20.10, ^22, ^24, ">=25" ] } }
    runs-on: ubuntu-latest

    steps:
    - { name: Checkout, uses: actions/checkout@v6 }

    - name: Setup Node.js ${{matrix.node-version}} environment
      uses: actions/setup-node@v6
      with: { node-version: "${{matrix.node-version}}" }

    - { name: Setup pnpm, uses: pnpm/action-setup@v4, with: { version: ^10, run_install: true } }
    - run: scripts/npm.sh
    - run: scripts/test.sh
